### ISSUE TITLE
64 java不能运行？Unable to attach to 32-bit process running under ！

### ISSUE THREAD

**Issue by PP9995** [BeichenDream/InjectJDBC#1]
Exception in thread "main" com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit process running under WOW64
        at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:56)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:70)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
        at com.abc.Main.main(Main.java from InputFileObject:39)

**Comment by BeichenDream** [comment]
目标进程是32位的，你运行的时候也要用32位，在```C:\Program Files (x86)\Java```找找看
